#ifndef  __CONFIG_H__
#include "config_efm32.h"

#define XTAL_FREQUENCY 48000000UL

#define SECURE_RAM_SIZE_BITS 12
#define SECURE_RAM_SIZE (1UL<<SECURE_RAM_SIZE_BITS)
#define STACK_POINTER (RAM_MEM_BASE+SECURE_RAM_SIZE)

#define SECURE_FLASH_SIZE_BITS 12
#define SECURE_FLASH_SIZE (1UL<<SECURE_FLASH_SIZE_BITS)

#endif /*__CONFIG_H__*/
