#ifndef  __CONFIG_H__

#include <uvisor-config.h>

#define CHANNEL_DEBUG 1
#define XTAL_FREQUENCY 48000000UL

#define USE_FLASH_SIZE UVISOR_FLASH_SIZE
#define USE_SRAM_SIZE  UVISOR_SRAM_SIZE

#define SRAM_REGIONS 8
#define STACK_GUARD_BAND_SIZE (USE_SRAM_SIZE/SRAM_REGIONS)

#define STACK_POINTER (USE_SRAM_SIZE-STACK_GUARD_BAND_SIZE)
#define STACK_MINIMUM_SIZE 2048

#endif /*__CONFIG_H__*/
